apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: contact-backend
    version: v1
spec:
  replicas: 1  # Single replica for free tier
  selector:
    matchLabels:
      app: contact-backend
  template:
    metadata:
      labels:
        app: contact-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: us.icr.io/contact-management/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant-credentials
              key: url
        - name: CLOUDANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudant-credentials
              key: apikey
        - name: CLOUDANT_DATABASE
          value: "contacts_db"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: contact-backend
spec:
  selector:
    app: contact-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
