apiVersion: v1
kind: Secret
metadata:
  name: cloudant-credentials
type: Opaque
data:
  # Base64 encoded values - replace with your actual credentials
  # To encode: echo -n "your-value" | base64
  url: eW91ci1jbG91ZGFudC11cmw=  # your-cloudant-url
  apikey: eW91ci1jbG91ZGFudC1hcGlrZXk=  # your-cloudant-apikey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  database_name: "contacts_db"
  log_level: "INFO"
  environment: "production"
